name: hously_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  beamer: ^1.7.0
  cached_network_image: ^3.3.1
  carousel_slider: ^5.0.0
  collection: ^1.18.0
  cookie_jar: ^4.0.8
  country_code_picker: ^3.2.0
  country_flags: ^3.2.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  device_info_plus: ^11.3.0
  dio: ^5.4.1
  dio_cookie_manager: ^3.1.1
  drag_and_drop_lists: ^0.4.1
  dropdown_button2: ^2.3.9
  equatable: ^2.0.5
  feedback:
    path: feedback
  file_picker: ^9.2.0
  fl_chart: ^0.70.2
  flag: ^7.0.0
  flex_color_scheme: ^8.0.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_colorpicker: ^1.1.0
  flutter_device_type: ^0.4.0
  flutter_draggable_list: ^1.0.2
  flutter_facebook_auth: ^7.0.0
  flutter_image_compress: ^2.3.0
  flutter_lints: ^5.0.0
  flutter_local_notifications: ^19.0.0
  flutter_localizations:
    sdk: flutter
  flutter_map: ^8.0.0
  flutter_map_cancellable_tile_provider: ^3.1.0
  flutter_quill: ^11.1.0
  flutter_riverpod: ^2.4.10
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.16
  flutter_switch: ^0.3.2
  flutter_typeahead: ^5.2.0
  fluttertoast: ^8.2.8
  font_awesome_flutter: ^10.7.0
  geolocator: ^13.0.2
  get: ^4.6.6
  google_fonts: ^6.2.1
  google_places_autocomplete_text_field: ^1.0.0
  google_sign_in: ^6.2.1
  html: ^0.15.4
  http: ^1.2.0
  image: ^4.1.7
  image_picker: ^1.1.2
  infinite_scroll_pagination: ^4.1.0
  int_to_words: ^0.0.4
  internet_connection_checker: ^3.0.1
  intl: ^0.19.0
#  js: ^0.6.7
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  latlong2: ^0.9.0
  material: any
  meta_seo: ^3.0.9
  nominatim_flutter: ^0.0.2
  pdf: ^3.6.1
  photo_view: ^0.15.0
  pie_menu: ^3.1.3
  printing: ^5.14.0
  provider: ^6.1.1
  responsive_ui: ^3.0.1
  riverpod: ^2.5.0
  rxdart: ^0.28.0
  searchable_listview: ^2.16.0
  sentry_flutter: ^8.10.1
  share_plus: ^10.1.4
  shared_preferences: ^2.3.3
  shimmer: ^3.0.0
  showcaseview: ^4.0.1
  sign_in_with_apple: ^6.1.0
  syncfusion_flutter_calendar: ^28.2.9
  syncfusion_flutter_core: ^28.2.9
  table_calendar: ^3.0.9
  toggle_switch: ^2.3.0
  universal_html: ^2.2.4
  web: ^1.0.0
  flutter_dropzone: ^4.2.1

  firebase_analytics: ^11.3.0
  firebase_core: ^3.4.0
  firebase_messaging: ^15.1.0
  dotted_border: ^2.1.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/view/
    - assets/images/deafult/
    - assets/countries.json
    - assets/icons/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/MontserratRegular.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf
          weight: 900
    - family: DejaVuSans
      fonts:
        - asset: assets/fonts/DejaVuSans.ttf
          weight: 900
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages