import 'package:hously_flutter/screens/go_pro/pc/components/go_pro_model.dart';

final subscriptionPackages = [
  SubscriptionPackage(
    features: {
      'standard': {
        'standardaccess': true,
        'prioritysupport': true,
        'exclusivefeatures': false,
        'boostprouctivity': false,
        'table': true,
        'disc': '8GB',
        'priority':false,
        'exclusive':true,
      },
      'gold': {
        'standardaccess': true,
        'prioritysupport': true,
        'exclusivefeatures': true,
        'boostprouctivity': false,
        'table': true,
        'disc': '20GB',
        'priority':false,
        'exclusive':true,
      },
      'premium': {
        'standardaccess': false,
        'prioritysupport': true,
        'exclusivefeatures': false,
        'boostprouctivity': false,
        'table': true,
        'disc': '2GB',
        'priority':false,
        'exclusive':true,
      }
    },
    name: "Agent Pro Plan",
    user: "Agent",
    userCategory: "AGENT",
    discountPrice: '\$ 79.99',
    price: '\$ 99.99',
    description: "Exclusive tools and analytics for real estate agents.",
    group: "Agent Group",
    started: true,
    validityTimeType: "M",
    validity: 6,
    forAllUsers: false,
    dateCreated: DateTime.now().subtract(Duration(days: 10)),
    lastUpdated: DateTime.now(),
  ),
  SubscriptionPackage(
    features: {
      'standard': {
        'standardaccess': true,
        'prioritysupport': true,
        'exclusivefeatures': false,
        'boostprouctivity': false,
        'table': true,
        'disc': '5GB',
        'priority':false,
        'exclusive':true,
      },
      'gold': {
        'standardaccess': true,
        'prioritysupport': true,
        'exclusivefeatures': true,
        'boostprouctivity': false,
        'table': true,
        'disc': '1GB',
        'priority':false,
        'exclusive':true,
      },
      'premium': {
        'standardaccess': false,
        'prioritysupport': true,
        'exclusivefeatures': false,
        'boostprouctivity': false,
        'table': true,
        'disc': '21GB',
        'priority':false,
        'exclusive':true,
      }
    },
    name: "Investor Growth Plan",
    user: "Investor",
    userCategory: "INVESTOR",
    discountPrice: '\$ 129.99',
    price: '\$ 149.99',
    description:
        "Detailed investment insights and personalized recommendations.",
    group: "Investor Group",
    started: true,
    validityTimeType: "Y",
    validity: 1,
    forAllUsers: false,
    dateCreated: DateTime.now().subtract(Duration(days: 20)),
    lastUpdated: DateTime.now(),
  ),
  SubscriptionPackage(
    features: {
      'standard': {
        'standardaccess': false,
        'prioritysupport': false,
        'exclusivefeatures': false,
        'boostprouctivity': false,
        'table': true,
        'disc': '10GB',
        'priority':false,
        'exclusive':true,
      },
      'gold': {
        'standardaccess': true,
        'prioritysupport': true,
        'exclusivefeatures': true,
        'boostprouctivity': false,
        'table': true,
        'disc': '4GB',
        'priority':false,
        'exclusive':true,
      },
      'premium': {
        'standardaccess': false,
        'prioritysupport': false,
        'exclusivefeatures': false,
        'boostprouctivity': false,
        'table': false,
        'disc': '7GB',
        'priority':false,
        'exclusive':true,
      }
    },
    name: "Individual Basic Plan",
    user: "Individual",
    userCategory: "INDIVIDUAL",
    discountPrice: '\$ 49.99',
    price: '\$ 59.99',
    description: "Basic tools and features for individual users.",
    group: "Individual Group",
    started: true,
    validityTimeType: "M",
    validity: 3,
    forAllUsers: true,
    dateCreated: DateTime.now().subtract(Duration(days: 5)),
    lastUpdated: DateTime.now(),
  ),
  SubscriptionPackage(
    features: {
      'standard': {
        'standardaccess': true,
        'prioritysupport': true,
        'exclusivefeatures': true,
        'boostprouctivity': true,
        'table': true,
        'disc': '1GB',
        'priority':false,
        'exclusive':true,
      },
      'gold': {
        'standardaccess': true,
        'prioritysupport': true,
        'exclusivefeatures': true,
        'boostprouctivity': true,
        'table': true,
        'disc': '2GB',
        'priority':false,
        'exclusive':true,
      },
      'premium': {
        'standardaccess': true,
        'prioritysupport': true,
        'exclusivefeatures': true,
        'boostprouctivity': true,
        'table': true,
        'disc': '4GB',
        'priority':false,
        'exclusive':true,
      }
    },
    name: "Landlord Premium Plan",
    user: "Landlord",
    userCategory: "LANDLORD",
    discountPrice: '\$ 99.99',
    price: '\$ 129.99',
    description: "Property management tools for landlords.",
    group: "Landlord Group",
    started: true,
    validityTimeType: "M",
    validity: 12,
    forAllUsers: false,
    dateCreated: DateTime.now().subtract(Duration(days: 15)),
    lastUpdated: DateTime.now(),
  ),
];
