import 'package:flutter/material.dart';

import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:get/get.dart';
import 'package:hously_flutter/screens/settings/mobile/profile/settings_profile_mobile.dart';
import 'package:hously_flutter/screens/settings/pc/Notifications/settings_notification_pc.dart';
import 'package:hously_flutter/screens/settings/pc/Security&privacy/settings_securityprivacy_pc.dart';
import 'package:hously_flutter/screens/settings/pc/chats/settings_chats_pc.dart';
import 'package:hously_flutter/screens/settings/pc/language/settings_language_pc.dart';
import 'package:hously_flutter/screens/settings/pc/logout/settings_lopgout_pc.dart';
import 'package:hously_flutter/screens/settings/pc/payments/settings_payment_pc.dart';
import 'package:hously_flutter/screens/settings/pc/profile/settings_profile_pc.dart';
import 'package:hously_flutter/screens/settings/pc/support/settings_support_pc.dart';
import 'package:hously_flutter/screens/settings/pc/themescreen/settings_theme_pc.dart';

class CalendarConst {
  static const monthsName = [
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
    'August',
    'September',
    'October',
    'November',
    'December',
  ];
}

final home1 = Provider<GlobalKey>((ref) => GlobalKey());
final home2 = Provider<GlobalKey>((ref) => GlobalKey());
final home3 = Provider<GlobalKey>((ref) => GlobalKey());
final home4 = Provider<GlobalKey>((ref) => GlobalKey());
final home5 = Provider<GlobalKey>((ref) => GlobalKey());
final home6 = Provider<GlobalKey>((ref) => GlobalKey());
final home7 = Provider<GlobalKey>((ref) => GlobalKey());

final crm1 = Provider<GlobalKey>((ref) => GlobalKey());
final crm2 = Provider<GlobalKey>((ref) => GlobalKey());
final crm3 = Provider<GlobalKey>((ref) => GlobalKey());
final crm4 = Provider<GlobalKey>((ref) => GlobalKey());
final crm5 = Provider<GlobalKey>((ref) => GlobalKey());
final crm6 = Provider<GlobalKey>((ref) => GlobalKey());
final crm7 = Provider<GlobalKey>((ref) => GlobalKey());

/// List of countries with their names, ISO codes for flags, and dial codes.
const countries = [
  {'name': 'Afghanistan', 'flag': 'AF', 'dialCode': '+93'},
  {'name': 'Albania', 'flag': 'AL', 'dialCode': '+355'},
  {'name': 'Algeria', 'flag': 'DZ', 'dialCode': '+213'},
  {'name': 'Andorra', 'flag': 'AD', 'dialCode': '+376'},
  {'name': 'Angola', 'flag': 'AO', 'dialCode': '+244'},
  {'name': 'Antigua and Barbuda', 'flag': 'AG', 'dialCode': '+1-268'},
  {'name': 'Argentina', 'flag': 'AR', 'dialCode': '+54'},
  {'name': 'Armenia', 'flag': 'AM', 'dialCode': '+374'},
  {'name': 'Australia', 'flag': 'AU', 'dialCode': '+61'},
  {'name': 'Austria', 'flag': 'AT', 'dialCode': '+43'},
  {'name': 'Azerbaijan', 'flag': 'AZ', 'dialCode': '+994'},
  {'name': 'Bahamas', 'flag': 'BS', 'dialCode': '+1-242'},
  {'name': 'Bahrain', 'flag': 'BH', 'dialCode': '+973'},
  {'name': 'Bangladesh', 'flag': 'BD', 'dialCode': '+880'},
  {'name': 'Barbados', 'flag': 'BB', 'dialCode': '+1-246'},
  {'name': 'Belarus', 'flag': 'BY', 'dialCode': '+375'},
  {'name': 'Belgium', 'flag': 'BE', 'dialCode': '+32'},
  {'name': 'Belize', 'flag': 'BZ', 'dialCode': '+501'},
  {'name': 'Benin', 'flag': 'BJ', 'dialCode': '+229'},
  {'name': 'Bhutan', 'flag': 'BT', 'dialCode': '+975'},
  {'name': 'Bolivia', 'flag': 'BO', 'dialCode': '+591'},
  {'name': 'Bosnia and Herzegovina', 'flag': 'BA', 'dialCode': '+387'},
  {'name': 'Botswana', 'flag': 'BW', 'dialCode': '+267'},
  {'name': 'Brazil', 'flag': 'BR', 'dialCode': '+55'},
  {'name': 'Brunei', 'flag': 'BN', 'dialCode': '+673'},
  {'name': 'Bulgaria', 'flag': 'BG', 'dialCode': '+359'},
  {'name': 'Burkina Faso', 'flag': 'BF', 'dialCode': '+226'},
  {'name': 'Burundi', 'flag': 'BI', 'dialCode': '+257'},
  {'name': 'Cabo Verde', 'flag': 'CV', 'dialCode': '+238'},
  {'name': 'Cambodia', 'flag': 'KH', 'dialCode': '+855'},
  {'name': 'Cameroon', 'flag': 'CM', 'dialCode': '+237'},
  {'name': 'Canada', 'flag': 'CA', 'dialCode': '+1'},
  {'name': 'Central African Republic', 'flag': 'CF', 'dialCode': '+236'},
  {'name': 'Chad', 'flag': 'TD', 'dialCode': '+235'},
  {'name': 'Chile', 'flag': 'CL', 'dialCode': '+56'},
  {'name': 'China', 'flag': 'CN', 'dialCode': '+86'},
  {'name': 'Colombia', 'flag': 'CO', 'dialCode': '+57'},
  {'name': 'Comoros', 'flag': 'KM', 'dialCode': '+269'},
  {'name': 'Congo (Congo-Brazzaville)', 'flag': 'CG', 'dialCode': '+242'},
  {'name': 'Congo (Democratic Republic)', 'flag': 'CD', 'dialCode': '+243'},
  {'name': 'Costa Rica', 'flag': 'CR', 'dialCode': '+506'},
  {'name': 'Croatia', 'flag': 'HR', 'dialCode': '+385'},
  {'name': 'Cuba', 'flag': 'CU', 'dialCode': '+53'},
  {'name': 'Cyprus', 'flag': 'CY', 'dialCode': '+357'},
  {'name': 'Czech Republic', 'flag': 'CZ', 'dialCode': '+420'},
  {'name': 'Denmark', 'flag': 'DK', 'dialCode': '+45'},
  {'name': 'Djibouti', 'flag': 'DJ', 'dialCode': '+253'},
  {'name': 'Dominica', 'flag': 'DM', 'dialCode': '+1-767'},
  {'name': 'Dominican Republic', 'flag': 'DO', 'dialCode': '+1-809'},
  {'name': 'Ecuador', 'flag': 'EC', 'dialCode': '+593'},
  {'name': 'Egypt', 'flag': 'EG', 'dialCode': '+20'},
  {'name': 'El Salvador', 'flag': 'SV', 'dialCode': '+503'},
  {'name': 'Equatorial Guinea', 'flag': 'GQ', 'dialCode': '+240'},
  {'name': 'Eritrea', 'flag': 'ER', 'dialCode': '+291'},
  {'name': 'Estonia', 'flag': 'EE', 'dialCode': '+372'},
  {'name': 'Eswatini', 'flag': 'SZ', 'dialCode': '+268'},
  {'name': 'Ethiopia', 'flag': 'ET', 'dialCode': '+251'},
  {'name': 'Fiji', 'flag': 'FJ', 'dialCode': '+679'},
  {'name': 'Finland', 'flag': 'FI', 'dialCode': '+358'},
  {'name': 'France', 'flag': 'FR', 'dialCode': '+33'},
  {'name': 'Gabon', 'flag': 'GA', 'dialCode': '+241'},
  {'name': 'Gambia', 'flag': 'GM', 'dialCode': '+220'},
  {'name': 'Georgia', 'flag': 'GE', 'dialCode': '+995'},
  {'name': 'Germany', 'flag': 'DE', 'dialCode': '+49'},
  {'name': 'Ghana', 'flag': 'GH', 'dialCode': '+233'},
  {'name': 'Greece', 'flag': 'GR', 'dialCode': '+30'},
  {'name': 'Grenada', 'flag': 'GD', 'dialCode': '+1-473'},
  {'name': 'Guatemala', 'flag': 'GT', 'dialCode': '+502'},
  {'name': 'Guinea', 'flag': 'GN', 'dialCode': '+224'},
  {'name': 'Guinea-Bissau', 'flag': 'GW', 'dialCode': '+245'},
  {'name': 'Guyana', 'flag': 'GY', 'dialCode': '+592'},
  {'name': 'Haiti', 'flag': 'HT', 'dialCode': '+509'},
  {'name': 'Honduras', 'flag': 'HN', 'dialCode': '+504'},
  {'name': 'Hungary', 'flag': 'HU', 'dialCode': '+36'},
  {'name': 'Iceland', 'flag': 'IS', 'dialCode': '+354'},
  {'name': 'India', 'flag': 'IN', 'dialCode': '+91'},
  {'name': 'Indonesia', 'flag': 'ID', 'dialCode': '+62'},
  {'name': 'Iran', 'flag': 'IR', 'dialCode': '+98'},
  {'name': 'Iraq', 'flag': 'IQ', 'dialCode': '+964'},
  {'name': 'Ireland', 'flag': 'IE', 'dialCode': '+353'},
  {'name': 'Israel', 'flag': 'IL', 'dialCode': '+972'},
  {'name': 'Italy', 'flag': 'IT', 'dialCode': '+39'},
  {'name': 'Jamaica', 'flag': 'JM', 'dialCode': '+1-876'},
  {'name': 'Japan', 'flag': 'JP', 'dialCode': '+81'},
  {'name': 'Jordan', 'flag': 'JO', 'dialCode': '+962'},
  {'name': 'Kazakhstan', 'flag': 'KZ', 'dialCode': '+7'},
  {'name': 'Kenya', 'flag': 'KE', 'dialCode': '+254'},
  {'name': 'Kiribati', 'flag': 'KI', 'dialCode': '+686'},
  {'name': 'Korea (North)', 'flag': 'KP', 'dialCode': '+850'},
  {'name': 'Korea (South)', 'flag': 'KR', 'dialCode': '+82'},
  {'name': 'Kuwait', 'flag': 'KW', 'dialCode': '+965'},
  {'name': 'Kyrgyzstan', 'flag': 'KG', 'dialCode': '+996'},
  {'name': 'Laos', 'flag': 'LA', 'dialCode': '+856'},
  {'name': 'Latvia', 'flag': 'LV', 'dialCode': '+371'},
  {'name': 'Lebanon', 'flag': 'LB', 'dialCode': '+961'},
  {'name': 'Lesotho', 'flag': 'LS', 'dialCode': '+266'},
  {'name': 'Liberia', 'flag': 'LR', 'dialCode': '+231'},
  {'name': 'Libya', 'flag': 'LY', 'dialCode': '+218'},
  {'name': 'Liechtenstein', 'flag': 'LI', 'dialCode': '+423'},
  {'name': 'Lithuania', 'flag': 'LT', 'dialCode': '+370'},
  {'name': 'Luxembourg', 'flag': 'LU', 'dialCode': '+352'},
  {'name': 'Madagascar', 'flag': 'MG', 'dialCode': '+261'},
  {'name': 'Malawi', 'flag': 'MW', 'dialCode': '+265'},
  {'name': 'Malaysia', 'flag': 'MY', 'dialCode': '+60'},
  {'name': 'Maldives', 'flag': 'MV', 'dialCode': '+960'},
  {'name': 'Mali', 'flag': 'ML', 'dialCode': '+223'},
  {'name': 'Malta', 'flag': 'MT', 'dialCode': '+356'},
  {'name': 'Marshall Islands', 'flag': 'MH', 'dialCode': '+692'},
  {'name': 'Mauritania', 'flag': 'MR', 'dialCode': '+222'},
  {'name': 'Mauritius', 'flag': 'MU', 'dialCode': '+230'},
  {'name': 'Mexico', 'flag': 'MX', 'dialCode': '+52'},
  {'name': 'Micronesia', 'flag': 'FM', 'dialCode': '+691'},
  {'name': 'Moldova', 'flag': 'MD', 'dialCode': '+373'},
  {'name': 'Monaco', 'flag': 'MC', 'dialCode': '+377'},
  {'name': 'Mongolia', 'flag': 'MN', 'dialCode': '+976'},
  {'name': 'Montenegro', 'flag': 'ME', 'dialCode': '+382'},
  {'name': 'Morocco', 'flag': 'MA', 'dialCode': '+212'},
  {'name': 'Mozambique', 'flag': 'MZ', 'dialCode': '+258'},
  {'name': 'Myanmar', 'flag': 'MM', 'dialCode': '+95'},
  {'name': 'Namibia', 'flag': 'NA', 'dialCode': '+264'},
  {'name': 'Nauru', 'flag': 'NR', 'dialCode': '+674'},
  {'name': 'Nepal', 'flag': 'NP', 'dialCode': '+977'},
  {'name': 'Netherlands', 'flag': 'NL', 'dialCode': '+31'},
  {'name': 'New Zealand', 'flag': 'NZ', 'dialCode': '+64'},
  {'name': 'Nicaragua', 'flag': 'NI', 'dialCode': '+505'},
  {'name': 'Niger', 'flag': 'NE', 'dialCode': '+227'},
  {'name': 'Nigeria', 'flag': 'NG', 'dialCode': '+234'},
  {'name': 'North Macedonia', 'flag': 'MK', 'dialCode': '+389'},
  {'name': 'Norway', 'flag': 'NO', 'dialCode': '+47'},
  {'name': 'Oman', 'flag': 'OM', 'dialCode': '+968'},
  {'name': 'Pakistan', 'flag': 'PK', 'dialCode': '+92'},
  {'name': 'Palau', 'flag': 'PW', 'dialCode': '+680'},
  {'name': 'Panama', 'flag': 'PA', 'dialCode': '+507'},
  {'name': 'Papua New Guinea', 'flag': 'PG', 'dialCode': '+675'},
  {'name': 'Paraguay', 'flag': 'PY', 'dialCode': '+595'},
  {'name': 'Peru', 'flag': 'PE', 'dialCode': '+51'},
  {'name': 'Philippines', 'flag': 'PH', 'dialCode': '+63'},
  {'name': 'Poland', 'flag': 'PL', 'dialCode': '+48'},
  {'name': 'Portugal', 'flag': 'PT', 'dialCode': '+351'},
  {'name': 'Qatar', 'flag': 'QA', 'dialCode': '+974'},
  {'name': 'Romania', 'flag': 'RO', 'dialCode': '+40'},
  {'name': 'Russia', 'flag': 'RU', 'dialCode': '+7'},
  {'name': 'Rwanda', 'flag': 'RW', 'dialCode': '+250'},
  {'name': 'Saint Kitts and Nevis', 'flag': 'KN', 'dialCode': '+1-869'},
  {'name': 'Saint Lucia', 'flag': 'LC', 'dialCode': '+1-758'},
  {
    'name': 'Saint Vincent and the Grenadines',
    'flag': 'VC',
    'dialCode': '+1-784'
  },
  {'name': 'Samoa', 'flag': 'WS', 'dialCode': '+685'},
  {'name': 'San Marino', 'flag': 'SM', 'dialCode': '+378'},
  {'name': 'Sao Tome and Principe', 'flag': 'ST', 'dialCode': '+239'},
  {'name': 'Saudi Arabia', 'flag': 'SA', 'dialCode': '+966'},
  {'name': 'Senegal', 'flag': 'SN', 'dialCode': '+221'},
  {'name': 'Serbia', 'flag': 'RS', 'dialCode': '+381'},
  {'name': 'Seychelles', 'flag': 'SC', 'dialCode': '+248'},
  {'name': 'Sierra Leone', 'flag': 'SL', 'dialCode': '+232'},
  {'name': 'Singapore', 'flag': 'SG', 'dialCode': '+65'},
  {'name': 'Slovakia', 'flag': 'SK', 'dialCode': '+421'},
  {'name': 'Slovenia', 'flag': 'SI', 'dialCode': '+386'},
  {'name': 'Solomon Islands', 'flag': 'SB', 'dialCode': '+677'},
  {'name': 'Somalia', 'flag': 'SO', 'dialCode': '+252'},
  {'name': 'South Africa', 'flag': 'ZA', 'dialCode': '+27'},
  {'name': 'South Sudan', 'flag': 'SS', 'dialCode': '+211'},
  {'name': 'Spain', 'flag': 'ES', 'dialCode': '+34'},
  {'name': 'Sri Lanka', 'flag': 'LK', 'dialCode': '+94'},
  {'name': 'Sudan', 'flag': 'SD', 'dialCode': '+249'},
  {'name': 'Suriname', 'flag': 'SR', 'dialCode': '+597'},
  {'name': 'Sweden', 'flag': 'SE', 'dialCode': '+46'},
  {'name': 'Switzerland', 'flag': 'CH', 'dialCode': '+41'},
  {'name': 'Syria', 'flag': 'SY', 'dialCode': '+963'},
  {'name': 'Taiwan', 'flag': 'TW', 'dialCode': '+886'},
  {'name': 'Tajikistan', 'flag': 'TJ', 'dialCode': '+992'},
  {'name': 'Tanzania', 'flag': 'TZ', 'dialCode': '+255'},
  {'name': 'Thailand', 'flag': 'TH', 'dialCode': '+66'},
  {'name': 'Timor-Leste', 'flag': 'TL', 'dialCode': '+670'},
  {'name': 'Togo', 'flag': 'TG', 'dialCode': '+228'},
  {'name': 'Tonga', 'flag': 'TO', 'dialCode': '+676'},
  {'name': 'Trinidad and Tobago', 'flag': 'TT', 'dialCode': '+1-868'},
  {'name': 'Tunisia', 'flag': 'TN', 'dialCode': '+216'},
  {'name': 'Turkey', 'flag': 'TR', 'dialCode': '+90'},
  {'name': 'Turkmenistan', 'flag': 'TM', 'dialCode': '+993'},
  {'name': 'Tuvalu', 'flag': 'TV', 'dialCode': '+688'},
  {'name': 'Uganda', 'flag': 'UG', 'dialCode': '+256'},
  {'name': 'Ukraine', 'flag': 'UA', 'dialCode': '+380'},
  {'name': 'United Arab Emirates', 'flag': 'AE', 'dialCode': '+971'},
  {'name': 'United Kingdom', 'flag': 'GB', 'dialCode': '+44'},
  {'name': 'United States', 'flag': 'US', 'dialCode': '+1'},
  {'name': 'Uruguay', 'flag': 'UY', 'dialCode': '+598'},
  {'name': 'Uzbekistan', 'flag': 'UZ', 'dialCode': '+998'},
  {'name': 'Vanuatu', 'flag': 'VU', 'dialCode': '+678'},
  {'name': 'Vatican City', 'flag': 'VA', 'dialCode': '+379'},
  {'name': 'Venezuela', 'flag': 'VE', 'dialCode': '+58'},
  {'name': 'Vietnam', 'flag': 'VN', 'dialCode': '+84'},
  {'name': 'Yemen', 'flag': 'YE', 'dialCode': '+967'},
  {'name': 'Zambia', 'flag': 'ZM', 'dialCode': '+260'},
  {'name': 'Zimbabwe', 'flag': 'ZW', 'dialCode': '+263'},
];

final mobilecodes = [
  const Locale("af"),
  const Locale("am"),
  const Locale("ar"),
  const Locale("az"),
  const Locale("be"),
  const Locale("bg"),
  const Locale("bn"),
  const Locale("bs"),
  const Locale("ca"),
  const Locale("cs"),
  const Locale("da"),
  const Locale("de"),
  const Locale("el"),
  const Locale("en"),
  const Locale("es"),
  const Locale("et"),
  const Locale("fa"),
  const Locale("fi"),
  const Locale("fr"),
  const Locale("gl"),
  const Locale("ha"),
  const Locale("he"),
  const Locale("hi"),
  const Locale("hr"),
  const Locale("hu"),
  const Locale("hy"),
  const Locale("id"),
  const Locale("is"),
  const Locale("it"),
  const Locale("ja"),
  const Locale("ka"),
  const Locale("kk"),
  const Locale("km"),
  const Locale("ko"),
  const Locale("ku"),
  const Locale("ky"),
  const Locale("lt"),
  const Locale("lv"),
  const Locale("mk"),
  const Locale("ml"),
  const Locale("mn"),
  const Locale("ms"),
  const Locale("nb"),
  const Locale("nl"),
  const Locale("nn"),
  const Locale("no"),
  const Locale("pl"),
  const Locale("ps"),
  const Locale("pt"),
  const Locale("ro"),
  const Locale("ru"),
  const Locale("sd"),
  const Locale("sk"),
  const Locale("sl"),
  const Locale("so"),
  const Locale("sq"),
  const Locale("sr"),
  const Locale("sv"),
  const Locale("ta"),
  const Locale("tg"),
  const Locale("th"),
  const Locale("tk"),
  const Locale("tr"),
  const Locale("tt"),
  const Locale("uk"),
  const Locale("ug"),
  const Locale("ur"),
  const Locale("uz"),
  const Locale("vi"),
  const Locale("zh")
];

final List<Map<String, String>> locations = [
  {
    'title': 'Location',
    'subtitle': 'All locations',
    'imagePath': 'assets/images/frame.png',
  },
  {
    'title': 'Property type',
    'subtitle': 'All property types',
    'imagePath': 'assets/images/frame.png',
  },
  {
    'title': 'Price range',
    'subtitle': 'Choose price range',
    'imagePath': 'assets/images/frame.png',
  },
  {
    'title': 'Meter range',
    'subtitle': 'Choose meter range',
    'imagePath': 'assets/images/frame.png',
  },
];

final estateFilters = [
  {'text': 'Mieszkanie', 'filterValue': 'Flat'},
  {'text': 'Kawalerka', 'filterValue': 'Studio'},
  {'text': 'Apartament', 'filterValue': 'Apartment'},
  {'text': 'Dom jednorodzinny', 'filterValue': 'House'},
  {'text': 'Bliźniak', 'filterValue': 'Twin house'},
  {'text': 'Szeregowiec', 'filterValue': 'Row house'},
  {'text': 'Inwestycje', 'filterValue': 'Invest'},
  {'text': 'Działki', 'filterValue': 'Lot'},
  {'text': 'Lokale użytkowe', 'filterValue': 'Commercial'},
  {'text': 'Hale i magazyny', 'filterValue': 'Warehouse'},
  {'text': 'Pokoje', 'filterValue': 'Room'},
  {'text': 'Garaże', 'filterValue': 'Garage'},
];

final roomFilters = [
  {'text': '1', 'filterValue': '1'},
  {'text': '2', 'filterValue': '2'},
  {'text': '3', 'filterValue': '3'},
  {'text': '4', 'filterValue': '4'},
  {'text': '5', 'filterValue': '5'},
];

final additionalFilters = [
  {'text': 'Balkon'.tr, 'filterKey': 'balcony'},
  {'text': 'Taras'.tr, 'filterKey': 'terrace'},
  {'text': 'Piwnica'.tr, 'filterKey': 'basement'},
  {'text': 'Winda'.tr, 'filterKey': 'elevator'},
  {'text': 'Ogród'.tr, 'filterKey': 'garden'},
  {'text': 'Garaż'.tr, 'filterKey': 'garage'},
  {'text': 'Klimatyzacja'.tr, 'filterKey': 'air_conditioning'},
  {'text': 'Miejsce postojowe'.tr, 'filterKey': 'parking_space'},
  {'text': 'Jacuzzi', 'filterKey': 'jacuzzi'},
  {'text': 'Sauna', 'filterKey': 'sauna'},
];
