final List<Map<String, dynamic>> events = [
  {
    'title': 'Negotiation meeting',
    'date': DateTime(2025, 01, 17, 10, 30),
    'location': 'Warszawa, Mokotów, Poland',
    'priority': 'high'
  },
  {
    'title': 'Team Building Workshop',
    'date': DateTime(2025, 01, 18, 14, 0),
    'location': 'Kraków, Old Town, Poland',
    'priority': 'mnedium'
  },
  {
    'title': 'Product Launch',
    'date': DateTime(2025, 01, 20, 9, 0),
    'location': 'Warszawa, Śródmieście, Poland',
    'priority': 'low'
  },
  {
    'title': 'Negotiation meeting',
    'date': DateTime(2025, 01, 22, 10, 30),
    'location': 'Warszawa, Mokotów, Poland',
    'priority': 'high'
  },
  {
    'title': 'Year-End Review',
    'date': DateTime(2025, 01, 29, 15, 0),
    'location': 'Poznań, Stare Miasto, Poland',
    'priority': 'low'
  },
];
final List<Map<String, dynamic>> todo = [
  {
    'title': 'Negotiation meeting',
    'date': DateTime(2025, 01, 17, 10, 30),
    'location': 'Warszawa, Mokotów, Poland',
    'priority': 'high'
  },
  {
    'title': 'Team Building Workshop',
    'date': DateTime(2025, 01, 18, 14, 0),
    'location': 'Kraków, Old Town, Poland',
    'priority': 'medium'
  },
  {
    'title': 'Product Launch',
    'date': DateTime(2025, 01, 20, 9, 0),
    'location': 'Warszawa, Śródmieście, Poland',
    'priority': 'medium'
  },
  {
    'title': 'Negotiation meeting',
    'date': DateTime(2025, 01, 22, 10, 30),
    'location': 'Warszawa, Mokotów, Poland',
    'priority': 'high'
  },
  {
    'title': 'Year-End Review',
    'date': DateTime(2025, 01, 29, 15, 0),
    'location': 'Poznań, Stare Miasto, Poland',
    'priority': 'medium'
  },
];
final List<Map<String, String>> transactions = [
  {
    'project': 'Parker Rd. Allentown',
    'type': 'SALE',
    'amounteuro': '€95,000',
    'commisioneuro': '€95,000',
    'location': 'Warszawa, Mokotów, Poland',
    'status': 'Pending',
    'amount': '\$100,000',
    'commission': '\$20,000',
    'date': '01-02-2025',
    'method': 'Credit Card',
    'cardno': '*****56565',
    'reason': 'Awaiting payment confirmation',
  },
  {
    'project': 'Maple St. Project',
    'type': 'RENT',
    'amounteuro': '€1,200',
    'commisioneuro': '€120',
    'location': 'Berlin, Mitte, Germany',
    'status': 'Cancel',
    'amount': '\$1,500',
    'commission': '\$150',
    'date': '15-01-2025',
    'method': 'Bank Transfer',
    'cardno': '*****12345',
    'reason': 'Client requested cancellation',
  },
  {
    'project': 'Sunset Blvd. Office',
    'type': 'SALE',
    'amounteuro': '€250,000',
    'commisioneuro': '€25,000',
    'location': 'New York, Manhattan, USA',
    'status': 'Success',
    'amount': '\$300,000',
    'commission': '\$30,000',
    'date': '20-01-2025',
    'method': 'Cheque',
    'cardno': '*****67890',
  },
  {
    'project': 'Broadway Ave. Residential',
    'type': 'RENT',
    'amounteuro': '€2,500',
    'commisioneuro': '€250',
    'location': 'Paris, Île-de-France, France',
    'status': 'Pending',
    'amount': '\$3,000',
    'commission': '\$300',
    'date': '10-01-2025',
    'method': 'Cash',
    'cardno': '*****11223',
    'reason': 'Lease agreement under review',
  },
  {
    'project': 'Palm Grove Villas',
    'type': 'SALE',
    'amounteuro': '€120,000',
    'commisioneuro': '€12,000',
    'location': 'Barcelona, Catalonia, Spain',
    'status': 'Cancel',
    'amount': '\$130,000',
    'commission': '\$13,000',
    'date': '12-01-2025',
    'method': 'Bank Transfer',
    'cardno': '*****44567',
    'reason': 'Funding issue from buyer',
  },
  {
    'project': 'Lakeside Office Park',
    'type': 'SALE',
    'amounteuro': '€800,000',
    'commisioneuro': '€80,000',
    'location': 'Tokyo, Chiyoda, Japan',
    'status': 'Pending',
    'amount': '\$850,000',
    'commission': '\$85,000',
    'date': '30-01-2025',
    'method': 'Online Payment',
    'cardno': '*****21345',
    'reason': 'Verification of ownership documents',
  },
  {
    'project': 'Central Plaza',
    'type': 'SALE',
    'amounteuro': '€500,000',
    'commisioneuro': '€50,000',
    'location': 'Singapore, Central Region',
    'status': 'Pending',
    'amount': '\$550,000',
    'commission': '\$55,000',
    'date': '28-01-2025',
    'method': 'Credit Card',
    'cardno': '*****55678',
    'reason': 'Bank processing delay',
  },
  {
    'project': 'Greenfield Heights',
    'type': 'RENT',
    'amounteuro': '€2,000',
    'commisioneuro': '€200',
    'location': 'Los Angeles, California, USA',
    'status': 'Cancel',
    'amount': '\$2,200',
    'commission': '\$220',
    'date': '25-01-2025',
    'method': 'Bank Transfer',
    'cardno': '*****99876',
    'reason': 'Tenant failed background check',
  },
  {
    'project': 'Parker Rd. Allentown',
    'type': 'SALE',
    'amounteuro': '€95,000',
    'commisioneuro': '€95,000',
    'location': 'Warszawa, Mokotów, Poland',
    'status': 'Pending',
    'amount': '\$100,000',
    'commission': '\$20,000',
    'date': '01-02-2025',
    'method': 'Credit Card',
    'cardno': '*****56565',
    'reason': 'Awaiting payment confirmation',
  },
  {
    'project': 'Maple St. Project',
    'type': 'RENT',
    'amounteuro': '€1,200',
    'commisioneuro': '€120',
    'location': 'Berlin, Mitte, Germany',
    'status': 'Cancel',
    'amount': '\$1,500',
    'commission': '\$150',
    'date': '15-01-2025',
    'method': 'Bank Transfer',
    'cardno': '*****12345',
    'reason': 'Client requested cancellation',
  },
  {
    'project': 'Sunset Blvd. Office',
    'type': 'SALE',
    'amounteuro': '€250,000',
    'commisioneuro': '€25,000',
    'location': 'New York, Manhattan, USA',
    'status': 'Success',
    'amount': '\$300,000',
    'commission': '\$30,000',
    'date': '20-01-2025',
    'method': 'Cheque',
    'cardno': '*****67890',
  },
  {
    'project': 'Parker Rd. Allentown',
    'type': 'SALE',
    'amounteuro': '€95,000',
    'commisioneuro': '€95,000',
    'location': 'Warszawa, Mokotów, Poland',
    'status': 'Pending',
    'amount': '\$100,000',
    'commission': '\$20,000',
    'date': '01-02-2025',
    'method': 'Credit Card',
    'cardno': '*****56565',
    'reason': 'Awaiting payment confirmation',
  },
  {
    'project': 'Maple St. Project',
    'type': 'RENT',
    'amounteuro': '€1,200',
    'commisioneuro': '€120',
    'location': 'Berlin, Mitte, Germany',
    'status': 'Cancel',
    'amount': '\$1,500',
    'commission': '\$150',
    'date': '15-01-2025',
    'method': 'Bank Transfer',
    'cardno': '*****12345',
    'reason': 'Client requested cancellation',
  },
  {
    'project': 'Sunset Blvd. Office',
    'type': 'SALE',
    'amounteuro': '€250,000',
    'commisioneuro': '€25,000',
    'location': 'New York, Manhattan, USA',
    'status': 'Success',
    'amount': '\$300,000',
    'commission': '\$30,000',
    'date': '20-01-2025',
    'method': 'Cheque',
    'cardno': '*****67890',
  },
];
